"""create jobs availability applications

Revision ID: 658771f39e2e
Revises: 7cb889724d42
Create Date: 2026-09-15 18:26:44.881913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models import Geography


# revision identifiers, used by Alembic.
revision: str = '658771f39e2e'
down_revision: Union[str, Sequence[str], None] = '7cb889724d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Image postgis/postgis bật sẵn extension, Postgres managed của Render thì không
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_intervals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_seeker_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_availability_time_range'),
    sa.ForeignKeyConstraint(['job_seeker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_intervals_job_seeker_id'), 'availability_intervals', ['job_seeker_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employer_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('location', Geography(), sa.Computed('ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography', persisted=True), nullable=True),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('time_end > time_start', name='ck_jobs_time_range'),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_employer_id'), 'jobs', ['employer_id'], unique=False)
    op.create_index('ix_jobs_location', 'jobs', ['location'], unique=False, postgresql_using='gist')
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('job_seeker_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['job_seeker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_job_seeker_id'), 'applications', ['job_seeker_id'], unique=False)
    op.create_index('uq_applications_active', 'applications', ['job_id', 'job_seeker_id'], unique=True, postgresql_where=sa.text("status <> 'cancelled'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_applications_active', table_name='applications', postgresql_where=sa.text("status <> 'cancelled'"))
    op.drop_index(op.f('ix_applications_job_seeker_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_jobs_location', table_name='jobs', postgresql_using='gist')
    op.drop_index(op.f('ix_jobs_employer_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_availability_intervals_job_seeker_id'), table_name='availability_intervals')
    op.drop_table('availability_intervals')
    # ### end Alembic commands ###
