"""add job address fields

Revision ID: ffbf3dd8cc02
Revises: 658771f39e2e
Create Date: 2026-09-15 19:21:10.807595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbf3dd8cc02'
down_revision: Union[str, Sequence[str], None] = '658771f39e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Tin đã có (chỉ có lat/lng) nhận chuỗi rỗng rồi bỏ default — tin mới bắt buộc gửi địa chỉ qua API
    for name, length in (("street", 200), ("ward", 100), ("city", 100)):
        op.add_column("jobs", sa.Column(name, sa.String(length=length), nullable=False, server_default=""))
        op.alter_column("jobs", name, server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'city')
    op.drop_column('jobs', 'ward')
    op.drop_column('jobs', 'street')
    # ### end Alembic commands ###
